spring:
  ai:
    mcp:
      server:
        name: search-picture-mcp-server
        version: 1.0.0
        #stdio
        stdio: true
        type: SYNC
  #stdio
  main:
    web-application-type: none
    banner-mode: off

