spring:
  application:
    name: ai-agent

  ai:
    client:
      default-system: 你是一个机票业务的专业人员，可以借助相关工具进行帮助AI大模型进行相关操作
    dashscope:
      knowledge-index: 面试
      base-url: https://dashscope.aliyuncs.com
      api-key: sk-f6dfb68603b64576b5194f33f7d0dbfe
      chat:
        options:
          model: qwen-plus
          temperature: 0.8
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 1536
      vision:
        options:
          model: qvq-max

  datasource:
    url: jdbc:postgresql://localhost:5432/vector_db
    username: admin
    password: 123456
    vector-store:
      pgvector:
        initialize-schema: true
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
        schema-name: public
        vector-table-name: airline_vector_store
  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.haitao.ai: debug
    org.springframework.ai.embedding: debug



# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.haitao.ai.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

forbidden:
  version: 1.0.0
  words:
    - 色情
    - 毒品
    - 赌博


